services:
  app:
    build:
      dockerfile: Dockerfile.dev
    command: bin/rails s
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:3000:3000
    stdin_open: true
    tty: true