FROM ruby:3.4.4

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libvips sqlite3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN bundle install